version: '3'
services:
  api:
    build: .
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: database
    env_file:
    - .env
  database:
    image: mongo
    ports:
      - "27017:27017"